services:
  - type: web
    name: pro-comply-backend
    runtime: python
    region: frankfurt
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: compliance-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: pro-comply.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://pro-comply.vercel.app
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: BREVO_EMAIL
        sync: false
      - key: BREVO_SMTP_KEY
        sync: false
    buildCommand: "powershell ./build.ps1"
    startCommand: "gunicorn Procomply.wsgi:application"
    healthCheckPath: "/api/accounts/test-auth/"

databases:
  - name: compliance-db
    databaseName: compliance
    user: postgres
    region: frankfurt